/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;



import code.Producto;
import code.Cliente;
import code.Pedido;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author jorge
 */
public class GUI_Principal extends javax.swing.JFrame {
    
    
    private static ArrayList<Producto> productos;
    private static ArrayList<Cliente> clientes;
    
   // Producto producto = new Producto();
   // Metodos metodos = new Metodos();
    
    /**
     * Creates new form GUI_Principal
     */
    DefaultTableModel mdlTabla;
    Vector vCabeceras = new Vector();
    
    public GUI_Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        productos = new ArrayList<Producto>(); 
         
        clientes = new ArrayList<Cliente>();
        
        cargarProductos();
        
        cargarClientes();
        
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_productos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_aniadir = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_editarCliente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_cliente = new javax.swing.JTable();
        btn_AgregarProducto = new javax.swing.JButton();
        lbl_numero = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_Copia = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Cafeteria");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Registro precio productos");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Cliente");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Pedidos");

        table_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Precio"
            }
        ));
        jScrollPane1.setViewportView(table_productos);

        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Crear pedido");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_aniadir.setText("Añadir");
        btn_aniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aniadirActionPerformed(evt);
            }
        });

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_editarCliente.setText("Editar");
        btn_editarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarClienteActionPerformed(evt);
            }
        });

        table_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Cedula"
            }
        ));
        jScrollPane2.setViewportView(table_cliente);

        btn_AgregarProducto.setText("Agregar producto");
        btn_AgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarProductoActionPerformed(evt);
            }
        });

        lbl_numero.setText("0");

        jLabel3.setText("productos agregados");

        btn_Copia.setText("Copia de seguridad");
        btn_Copia.setFocusable(false);
        btn_Copia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Copia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Copia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CopiaActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Acerca de...");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Mas informacion");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Salir");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Exit");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jRadioButtonMenuItem2);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_AgregarProducto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl_numero)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Copia))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_aniadir)
                                    .addGap(1, 1, 1)
                                    .addComponent(btn_editar)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_editarCliente))
                                .addComponent(jLabel6)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btn_aniadir)
                    .addComponent(btn_editar)
                    .addComponent(btn_editarCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(btn_AgregarProducto)
                            .addComponent(lbl_numero)
                            .addComponent(jLabel3)))
                    .addComponent(btn_Copia))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // TODO add your handling code here:
        //GUI_EditarProducto gui = new GUI_EditarProducto(this);
        //gui.show();
        
        int c, precio;
        Producto aux;
        try {
            c = table_productos.getSelectedRow();
            aux = productos.get(c);
            precio = Integer.parseInt(JOptionPane.showInputDialog("Nuevo precio!"));
            aux.setPrecio(precio);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Escoger una fila");
        }
        verDatosProductos();
        guardarProductos();
        
        JOptionPane.showMessageDialog(null, "Actualizado con exito!");
    }//GEN-LAST:event_btn_editarActionPerformed

   
    private void btn_aniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aniadirActionPerformed
        // TODO add your handling code here:
        
        GUI_AniadirProducto aniadir = new GUI_AniadirProducto(this);
        aniadir.show();
        
        //metodos.llenarTablaPedidos(();
        
    }//GEN-LAST:event_btn_aniadirActionPerformed

    public void aniadirProducto(String pNombre, double pPrecio){
        
        try{
            Producto p = new Producto(pNombre, pPrecio);
            productos.add(p);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Verifique sus datos");
        }
        
       
        verDatosProductos(); //Aca solomamente los muestra pero no los guarda
        guardarProductos(); //Aca los guarda
        
        JOptionPane.showMessageDialog(null, "Agregado con exito!");
    }
    
    public void aniadirCliente(String pId, double id){
        try{
            Cliente c = new Cliente(pId, id);
            clientes.add(c);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Verifique sus datos");
        }
        
        //limpiar(); //Limpiarlos en la pestaña!
        verDatosClientes();
        guardarClientes();
        
        JOptionPane.showMessageDialog(null, "Agregado con exito!");
    }
    
    /*
        Me gusta ver el precio sin punto, por eso tambien use mi metodo. 
        en la linea 367.
    */ 
    
    private void verDatosProductos(){
        String Mat[][] = new String[productos.size()][2]; //3
        Producto aux;
        for (int i = 0; i < productos.size(); i++) {
            aux = productos.get(i);
            Mat[i][0] = aux.getNombre();
            Mat[i][1] = quitarPunto(aux.getPrecio()) + "$";
            
        }
        table_productos.setModel(new javax.swing.table.DefaultTableModel(
            Mat, 
            new String [] {
                "Nombre", "Precio"
            }
        ));
        
    }
    
    /*Quizas te preguntes por que no use un String para guardar el numero,
      del cliente, la respuesta es porque sencillamente no funciona y solo Dios  
      sabe por que no jaja. Intente guardar el celular como int pero tampoco 
      funciono, por lo que decidi crear el metodo para que cuando viera un .
      lo quitara, junto con lo que venia (O sea el cero). Si alguien se quiere
      aventurar a cambiarlo, el celular como tipo String, y encuentra una solucion
      escribame a mi Instagram @jorge_315b y los saludo en el proximo video. 
      pdt: Perdon por la ortografia jaja.
    
      + Un celular como tal no lo puede guardar, ya que un double no guarda 
        tantos caracateres, por eso es mucho mejor pasarlo a String :/
        Pero bueno, la otra que se me ocurrio fue pasarlo a Long pero no me sirvio.
        
    */
    
    private String quitarPunto(double numero){
        
        String numeroString = numero + "";
        String nueva = "";
        for(int i = 0; i < numeroString.length(); i++){
            
            
            if(numeroString.charAt(i) == '.'){
                break;
            }
            nueva = nueva + numeroString.charAt(i) + "";
        }
        return nueva;
    }
    
    private void verDatosClientes(){ //Modificar
        String Mat[][] = new String[clientes.size()][2]; //3
        Cliente aux;
        for (int i = 0; i < clientes.size(); i++) {
            aux = clientes.get(i);
            Mat[i][0] = aux.getNombre();
            
            Mat[i][1] = quitarPunto(aux.getCelular());
            
        }
        table_cliente.setModel(new javax.swing.table.DefaultTableModel(
            Mat, 
            new String [] {
                "Nombre", "Celular"
            }
        ));
        
    }
    
    private void guardarProductos(){
        File file = new File("Productos.txt");
        PrintWriter Escribe;
        if(!file.exists()){
            try {
                file.createNewFile();
            } catch (Exception e) { 
            }
        }
        try {
            Producto aux;
            Escribe = new PrintWriter(file, "utf-8");
            for (int i = 0; i < productos.size(); i++) {
                aux = productos.get(i);
                aux.guardar(Escribe);
            }
            Escribe.close();
        } catch (Exception e) {
        }
    }
    
    private void copiaSeguridadProducto(){
           File file = new File("CopiaProductos.txt");
        PrintWriter Escribe;
        if(!file.exists()){
            try {
                file.createNewFile();
            } catch (Exception e) { 
            }
        }
        try {
            Producto aux;
            Escribe = new PrintWriter(file, "utf-8");
            for (int i = 0; i < productos.size(); i++) {
                aux = productos.get(i);
                aux.guardar(Escribe);
            }
            Escribe.close();
        } catch (Exception e) {
        }
    }
    
    private void guardarClientes(){
        File file = new File("Clientes.txt");
        PrintWriter Escribe;
        if(!file.exists()){
            try {
                file.createNewFile();
            } catch (Exception e) { 
            }
        }
        try {
            Cliente aux;
            Escribe = new PrintWriter(file, "utf-8");
            for (int i = 0; i < clientes.size(); i++) {
                aux = clientes.get(i);
                aux.guardar(Escribe);
            }
            Escribe.close();
        } catch (Exception e) {
        }
    }
    
     private void copiaSeguridadClientes(){
        File file = new File("CopiaClientes.txt");
        PrintWriter Escribe;
        if(!file.exists()){
            try {
                file.createNewFile();
            } catch (Exception e) { 
            }
        }
        try {
            Cliente aux;
            Escribe = new PrintWriter(file, "utf-8");
            for (int i = 0; i < clientes.size(); i++) {
                aux = clientes.get(i);
                aux.guardar(Escribe);
            }
            Escribe.close();
        } catch (Exception e) {
        }
    }
    
     public void cargarProductos(){
        File Archivo = new File("Productos.txt");
        FileReader Leer;
        BufferedReader Almacen;
        Producto per, aux = new Producto();
        try {
            Leer = new FileReader(Archivo);
            Almacen = new BufferedReader(Leer);
            per = aux.cargar(Almacen);
            
            while(per != null){ //Hasta que no llegue al final, no para
                productos.add(per);
                per = aux.cargar(Almacen);
            }
            Almacen.close();
            Leer.close();
        } catch (Exception e) {
            
        }
        verDatosProductos();
    }
     
    public void cargarClientes(){ 
        
        File Archivo = new File("Clientes.txt");
        
        FileReader Leer;
        BufferedReader Almacen;
        Cliente per;
        Cliente aux = new Cliente();
        
        try {
            Leer = new FileReader(Archivo);
            
            Almacen = new BufferedReader(Leer);
            per = aux.cargar(Almacen);
             
            while(per != null){ //Aca esta el hpta error.
               
                clientes.add(per);
                per = aux.cargar(Almacen);
                
            }
            
            Almacen.close();
            Leer.close();
            
        } catch (Exception e) {
            
        }
        verDatosClientes();
   
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //GUI_AniadirPedido aniadirPedido = new GUI_AniadirPedido();
        //aniadirPedido.show();
        GUI_Pedido pedido = new GUI_Pedido(productosInformacion, sumaDePedido,clientes,num);
        pedido.show();
        num = 0;
        
        lbl_numero.setText(num + "");
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void inforProductos(){
        
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GUI_AniadirCliente aniadirCliente = new GUI_AniadirCliente(this);
        aniadirCliente.show();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_editarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarClienteActionPerformed
        // TODO add your handling code here:
        int c; 
        double celular;
        Cliente aux;
        try {
            c = table_cliente.getSelectedRow();
            aux = clientes.get(c);
            celular = Double.parseDouble(JOptionPane.showInputDialog("Nuevo celular!"));
            aux.setCelular(celular);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Escoger una fila");
        }
        verDatosClientes();
        guardarClientes();
        
        JOptionPane.showMessageDialog(null, "Actualizado con exito!");
    }//GEN-LAST:event_btn_editarClienteActionPerformed
    
    double sumaDePedido = 0; //Aqui esta la variable magica jajajaj.
    int num = 0;
    String productosInformacion = "";
    private void btn_AgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarProductoActionPerformed
        // TODO add your handling code here:
        int c;
        Producto aux;
        try {
            c = table_productos.getSelectedRow();
            aux = productos.get(c);
            
            sumaDePedido = sumaDePedido + aux.getPrecio();
            
            productosInformacion = productosInformacion + "-" + aux.getNombre();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Escoger una fila");
        }
        verDatosProductos();
        guardarProductos();
        
        JOptionPane.showMessageDialog(null, "Agregado el producto al pedido con exito!");
        num++;
        
        lbl_numero.setText(num + "");
        
        
    }//GEN-LAST:event_btn_AgregarProductoActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        // TODO add your handling code here:
        GUI_AcercaDe acerca = new GUI_AcercaDe();
        acerca.show();
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void btn_CopiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CopiaActionPerformed
       
        copiaSeguridadProducto();
        copiaSeguridadClientes();
        
        JOptionPane.showMessageDialog(null, "Copia de seguridad creada con exito!");
        
    }//GEN-LAST:event_btn_CopiaActionPerformed
    
     private void copiaSeguridadPedidos(ArrayList array){
         
        File file = new File("CopiaPedidos.txt");
        PrintWriter Escribe;
        if(!file.exists()){
            try {
                file.createNewFile();
            } catch (Exception e) { 
            }
        }
        try {
            Pedido aux;
            Escribe = new PrintWriter(file, "utf-8");
            for (int i = 0; i < array.size(); i++) {
                aux = (Pedido) array.get(i);
                aux.guardar(Escribe);
            }
            Escribe.close();
        } catch (Exception e) {
        }
    }
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Principal().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AgregarProducto;
    private javax.swing.JButton btn_Copia;
    private javax.swing.JButton btn_aniadir;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_editarCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_numero;
    private javax.swing.JTable table_cliente;
    private javax.swing.JTable table_productos;
    // End of variables declaration//GEN-END:variables
}
